name: Infracost
on:
    workflow_dispatch:
jobs:
   # Run Infracost on default branch and update Infracost Cloud
    infracost-default-branch-update:
      # If you use private modules, or store Terraform variables or modules in a 3rd party
      # such as TFC or Spacelift, include the same steps/variables as the infracost-pull-request-checks job
      name: Infracost Default Branch Update
      runs-on: ubuntu-latest
      steps:
        - name: Setup Infracost
          uses: infracost/actions/setup@v3
          with:
            api-key: ${{ secrets.INFRACOST_API_KEY }}
  
        - name: Checkout main/master branch
          uses: actions/checkout@v4
  
        - name: Run Infracost on default branch and update Infracost Cloud
          run: |
            infracost breakdown \
                      --path=demo/ \
                      --terraform-var-file full.tfvars \
                      --format=json \
                      --out-file=infracost.json        
  
    # # Update PR status in Infracost Cloud
    # infracost-pull-request-status-update:
    #   name: Infracost PR Status Update
    #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Infracost PR Status Update
    #     run: |
    #       PR_STATUS="MERGED"
    #       if [[ ${{ github.event.pull_request.merged }} = false ]]; then PR_STATUS="CLOSED"; fi
  
    #       echo "Updating status of ${{ github.event.pull_request.html_url }} to $PR_STATUS"
    #       curl -i \
    #         --request POST \
    #         --header "Content-Type: application/json" \
    #         --header "X-API-Key: $INFRACOST_API_KEY" \
    #         --data "{ \"query\": \"mutation {updatePullRequestStatus( url: \\\"${{ github.event.pull_request.html_url }}\\\", status: $PR_STATUS )}\" }" \
    #         "https://dashboard.api.infracost.io/graphql";
    #     env:
    #       INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}    
    # This stage runs the Infracost CLI and posts PR comments.
    # It also updates PR comments when the PR is updated (synchronize event).
    # infracost-pull-request-checks:
    #   name: Infracost Pull Request Checks
    #   runs-on: ubuntu-latest
    #   permissions:
    #     contents: read
    #     pull-requests: write # Required to post comments
    #   steps:
    #     - name: Setup Infracost
    #       uses: infracost/actions/setup@v3
    #       # See https://github.com/infracost/actions/tree/master/setup for other inputs
    #       # If you can't use this action, use Docker image infracost/infracost:ci-0.10
    #       with:
    #         api-key: ${{ secrets.INFRACOST_API_KEY }}
  
    #     # Checkout the base branch of the pull request (e.g. main/master).
    #     - name: Checkout base branch
    #       uses: actions/checkout@v4
    #       with:
    #         ref: '${{ github.event.pull_request.base.ref }}'
  
    #     # Generate Infracost JSON file as the baseline.
    #     - name: Generate Infracost cost estimate baseline
    #       run: |
    #         infracost breakdown --path=demo/ \
    #                             --format=json \
    #                             --terraform-var-file full.tfvars \
    #                             --out-file=/tmp/infracost-base.json
  
    #     # Checkout the current PR branch so we can create a diff.
    #     - name: Checkout PR branch
    #       uses: actions/checkout@v4
  
    #     # Generate an Infracost diff and save it to a JSON file.
    #     - name: Generate Infracost diff
    #       run: |
    #         infracost diff --path=demo/ \
    #                         --format=json \
    #                         --terraform-var-file full.tfvars
    #                         --compare-to=/tmp/infracost-base.json \
    #                         --out-file=/tmp/infracost.json
  
    #     # Posts a comment to the PR using the 'update' behavior.
    #     # This creates a single comment and updates it. The "quietest" option.
    #     # The other valid behaviors are:
    #     #   delete-and-new - Delete previous comments and create a new one.
    #     #   hide-and-new - Minimize previous comments and create a new one.
    #     #   new - Create a new cost estimate comment on every push.
    #     # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
    #     - name: Post Infracost comment
    #       run: |
    #           infracost comment github --path=/tmp/infracost.json \
    #                                    --repo=$GITHUB_REPOSITORY \
    #                                    --github-token=${{ github.token }} \
    #                                    --pull-request=${{ github.event.pull_request.number }} \
    #                                    --behavior=update
  
    # # Run Infracost on default branch and update Infracost Cloud
    # infracost-default-branch-update:
    #   # If you use private modules, or store Terraform variables or modules in a 3rd party
    #   # such as TFC or Spacelift, include the same steps/variables as the infracost-pull-request-checks job
    #   name: Infracost Default Branch Update
    #   if: github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'master')
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Setup Infracost
    #       uses: infracost/actions/setup@v3
    #       with:
    #         api-key: ${{ secrets.INFRACOST_API_KEY }}
  
    #     - name: Checkout main/master branch
    #       uses: actions/checkout@v4
  
    #     - name: Run Infracost on default branch and update Infracost Cloud
    #       run: |
    #         infracost breakdown --path=. \
    #                   --format=json \
    #                   --out-file=infracost.json
  
    #         infracost upload --path=infracost.json || echo "Always pass main branch runs even if there are policy failures"
  
    # # Update PR status in Infracost Cloud
    # infracost-pull-request-status-update:
    #   name: Infracost PR Status Update
    #   if: github.event_name == 'pull_request' && github.event.action == 'closed'
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Infracost PR Status Update
    #     run: |
    #       PR_STATUS="MERGED"
    #       if [[ ${{ github.event.pull_request.merged }} = false ]]; then PR_STATUS="CLOSED"; fi
  
    #       echo "Updating status of ${{ github.event.pull_request.html_url }} to $PR_STATUS"
    #       curl -i \
    #         --request POST \
    #         --header "Content-Type: application/json" \
    #         --header "X-API-Key: $INFRACOST_API_KEY" \
    #         --data "{ \"query\": \"mutation {updatePullRequestStatus( url: \\\"${{ github.event.pull_request.html_url }}\\\", status: $PR_STATUS )}\" }" \
    #         "https://dashboard.api.infracost.io/graphql";
    #     env:
    #       INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}